### PR TITLE
Configuring URL patterns to external systems (#31)

### PR DESCRIPTION
**Pull request by volkovs**
Jenkins global settings to configure issue tracker and TMS URL patterns. Once accepted Job settings will be added.

### CODE REVIEW

**Comment by volkovs** [comment]
@eroshenkoam @vania-pooh 
Hi guys, did you manage to review this pull request? May be something else should be corrected?
(People keep asking on StackOverflow.)

**Comment by vania-pooh** [comment]
@volkovs We'll do this soon. Could you please rebase this PR?

**Comment by volkovs** [comment]
@vania-pooh Done

**Comment by baev** [comment]
@eroshenkoam @vania-pooh let's merge this, guys! WFT what are you waiting for?

**Comment by vania-pooh** [comment]
@baev :disappointed: okay

**Comment by vania-pooh** [comment]
Merged manually. Please send next pull requests to https://github.com/jenkinsci/allure-plugin/

**Comment by volkovs** [comment]
@vania-pooh OK, got it, thanks

**Comment by vania-pooh** [comment]
@volkovs hmm, we got troubles with your PR. My error. What we're getting it:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5:compile (default-compile) on project allure-jenkins-plugin: Compilation failure: Compilation failure:
[ERROR] /Users/vania-pooh/src/testing/allure-jenkins-plugin/src/main/java/ru/yandex/qatools/allure/jenkins/config/AllureGlobalConfig.java:[19,12] error: cannot find symbol
[ERROR] symbol:   class ProxySettingsConfig
[ERROR] location: class AllureGlobalConfig
[ERROR] /Users/vania-pooh/src/testing/allure-jenkins-plugin/src/main/java/ru/yandex/qatools/allure/jenkins/config/AllureGlobalConfig.java:[53,11] error: cannot find symbol
[ERROR] symbol:   class ProxySettingsConfig
[ERROR] location: class AllureGlobalConfig
[ERROR] /Users/vania-pooh/src/testing/allure-jenkins-plugin/src/main/java/ru/yandex/qatools/allure/jenkins/config/AllureGlobalConfig.java:[57,33] error: cannot find symbol
[ERROR] -> [Help 1]
[ERROR]
```
Could you please add respective class and send PR to repository above?

**Comment by volkovs** [comment]
@vania-pooh https://github.com/jenkinsci/allure-plugin/pull/9
(I couldn't find ProxySettingsConfig.java in allure-framework repo as well, so I deleted proxy settings, seems it wasn't used)

**Comment by vania-pooh** [comment]
Thanks a lot.

**Pull request merged**
